# Generated by Django 6.1.dev20251225180557 on 2025-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migration_test_data_persistence", "0002_add_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unmanaged",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
