# This file is distributed under the same license as the Django package.
#
# Translators:
# Michael Wolf <milupo@sorbzilla.de>, 2016-2025
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-03-19 11:30-0500\n"
"PO-Revision-Date: 2025-04-01 15:04-0500\n"
"Last-Translator: Michael Wolf <milupo@sorbzilla.de>, 2016-2025\n"
"Language-Team: Lower Sorbian (http://app.transifex.com/django/django/"
"language/dsb/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: dsb\n"
"Plural-Forms: nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || "
"n%100==4 ? 2 : 3);\n"

msgid "Afrikaans"
msgstr "Afrikaanšćina"

msgid "Arabic"
msgstr "Arabšćina"

msgid "Algerian Arabic"
msgstr "Algeriska arabšćina"

msgid "Asturian"
msgstr "Asturišćina"

msgid "Azerbaijani"
msgstr "Azerbajdžanišćina"

msgid "Bulgarian"
msgstr "Bulgaršćina"

msgid "Belarusian"
msgstr "Běłorušćina"

msgid "Bengali"
msgstr "Bengalšćina"

msgid "Breton"
msgstr "Bretońšćina"

msgid "Bosnian"
msgstr "Bosnišćina"

msgid "Catalan"
msgstr "Katalańšćina"

msgid "Central Kurdish (Sorani)"
msgstr "Centralna kurdišćina (Sorani)"

msgid "Czech"
msgstr "Češćina"

msgid "Welsh"
msgstr "Kymrišćina"

msgid "Danish"
msgstr "Dańšćina"

msgid "German"
msgstr "Nimšćina"

msgid "Lower Sorbian"
msgstr "Dolnoserbšćina"

msgid "Greek"
msgstr "Grichišćina"

msgid "English"
msgstr "Engelšćina"

msgid "Australian English"
msgstr "Awstralska engelšćina"

msgid "British English"
msgstr "Britiska engelšćina"

msgid "Esperanto"
msgstr "Esperanto"

msgid "Spanish"
msgstr "Špańšćina"

msgid "Argentinian Spanish"
msgstr "Argentinska špańšćina"

msgid "Colombian Spanish"
msgstr "Kolumbiska špańšćina"

msgid "Mexican Spanish"
msgstr "Mexikańska špańšćina"

msgid "Nicaraguan Spanish"
msgstr "Nikaraguaska špańšćina"

msgid "Venezuelan Spanish"
msgstr "Venezolaniska špańšćina"

msgid "Estonian"
msgstr "Estnišćina"

msgid "Basque"
msgstr "Baskišćina"

msgid "Persian"
msgstr "Persišćina"

msgid "Finnish"
msgstr "Finšćina"

msgid "French"
msgstr "Francojšćina"

msgid "Frisian"
msgstr "Frizišćina"

msgid "Irish"
msgstr "Iršćina"

msgid "Scottish Gaelic"
msgstr "Šotiska gelišćina"

msgid "Galician"
msgstr "Galicišćina"

msgid "Hebrew"
msgstr "Hebrejšćina"

msgid "Hindi"
msgstr "Hindišćina"

msgid "Croatian"
msgstr "Chorwatšćina"

msgid "Upper Sorbian"
msgstr "Górnoserbšćina"

msgid "Hungarian"
msgstr "Hungoršćina"

msgid "Armenian"
msgstr "Armeńšćina"

msgid "Interlingua"
msgstr "Interlingua"

msgid "Indonesian"
msgstr "Indonešćina"

msgid "Igbo"
msgstr "Igbo"

msgid "Ido"
msgstr "Ido"

msgid "Icelandic"
msgstr "Islandšćina"

msgid "Italian"
msgstr "Italšćina"

msgid "Japanese"
msgstr "Japańšćina"

msgid "Georgian"
msgstr "Georgišćina"

msgid "Kabyle"
msgstr "Kabylšćina"

msgid "Kazakh"
msgstr "Kazachšćina"

msgid "Khmer"
msgstr "Rěc Khmerow"

msgid "Kannada"
msgstr "Kannadišćina"

msgid "Korean"
msgstr "Korejańšćina"

msgid "Kyrgyz"
msgstr "Kirgišćina"

msgid "Luxembourgish"
msgstr "Luxemburgšćina"

msgid "Lithuanian"
msgstr "Litawšćina"

msgid "Latvian"
msgstr "Letišćina"

msgid "Macedonian"
msgstr "Makedońšćina"

msgid "Malayalam"
msgstr "Malajalam"

msgid "Mongolian"
msgstr "Mongolšćina"

msgid "Marathi"
msgstr "Marathi"

msgid "Malay"
msgstr "Malayzišćina"

msgid "Burmese"
msgstr "Myanmaršćina"

msgid "Norwegian Bokmål"
msgstr "Norwegski Bokmål"

msgid "Nepali"
msgstr "Nepalšćina"

msgid "Dutch"
msgstr "¨Nižozemšćina"

msgid "Norwegian Nynorsk"
msgstr "Norwegski Nynorsk"

msgid "Ossetic"
msgstr "Osetšćina"

msgid "Punjabi"
msgstr "Pundžabi"

msgid "Polish"
msgstr "Pólšćina"

msgid "Portuguese"
msgstr "Portugišćina"

msgid "Brazilian Portuguese"
msgstr "Brazilska portugišćina"

msgid "Romanian"
msgstr "Rumunšćina"

msgid "Russian"
msgstr "Rušćina"

msgid "Slovak"
msgstr "Słowakšćina"

msgid "Slovenian"
msgstr "Słowjeńšćina"

msgid "Albanian"
msgstr "Albanšćina"

msgid "Serbian"
msgstr "Serbišćina"

msgid "Serbian Latin"
msgstr "Serbišćina, łatyńska"

msgid "Swedish"
msgstr "Šwedšćina"

msgid "Swahili"
msgstr "Suahelšćina"

msgid "Tamil"
msgstr "Tamilšćina"

msgid "Telugu"
msgstr "Telugu"

msgid "Tajik"
msgstr "Tadźikišćina"

msgid "Thai"
msgstr "Thaišćina"

msgid "Turkmen"
msgstr "Turkmeńšćina"

msgid "Turkish"
msgstr "Turkojšćina"

msgid "Tatar"
msgstr "Tataršćina"

msgid "Udmurt"
msgstr "Udmurtšćina"

msgid "Uyghur"
msgstr "Ujguršćina"

msgid "Ukrainian"
msgstr "Ukrainšćina"

msgid "Urdu"
msgstr "Urdu"

msgid "Uzbek"
msgstr "Uzbekšćina"

msgid "Vietnamese"
msgstr "Vietnamšćina"

msgid "Simplified Chinese"
msgstr "Zjadnorjona chinšćina"

msgid "Traditional Chinese"
msgstr "Tradicionelna chinšćina"

msgid "Messages"
msgstr "Powěsći"

msgid "Site Maps"
msgstr "Wopśimjeśowy pśeglěd sedła"

msgid "Static Files"
msgstr "Statiske dataje"

msgid "Syndication"
msgstr "Syndikacija"

#. Translators: String used to replace omitted page numbers in elided page
#. range generated by paginators, e.g. [1, 2, '…', 5, 6, 7, '…', 9, 10].
msgid "…"
msgstr "…"

msgid "That page number is not an integer"
msgstr "Toś ten numer boka njejo ceła licba"

msgid "That page number is less than 1"
msgstr "Numer boka jo mjeńšy ako 1"

msgid "That page contains no results"
msgstr "Toś ten bok njewopśimujo wuslědki"

msgid "Enter a valid value."
msgstr "Zapódajśo płaśiwu gódnotu."

msgid "Enter a valid domain name."
msgstr "Zapódajśo płaśiwe domenowe mě."

msgid "Enter a valid URL."
msgstr "Zapódajśo płaśiwy URL."

msgid "Enter a valid integer."
msgstr "Zapódajśo płaśiwu cełu licbu."

msgid "Enter a valid email address."
msgstr "Zapódajśo płaśiwu e-mailowu adresu."

#. Translators: "letters" means latin letters: a-z and A-Z.
msgid ""
"Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."
msgstr ""
"Zapódajśo płaśiwe „adresowe mě“, kótarež jano wopśimujo pismiki, licby, "
"pódsmužki abo wězawki."

msgid ""
"Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or "
"hyphens."
msgstr ""
"Zapódajśo płaśiwe „adresowe mě“, kótarež jano wopśimujo unicodowe pismiki, "
"licby, pódmužki abo wězawki."

#, python-format
msgid "Enter a valid %(protocol)s address."
msgstr "Zapódajśo płaśiwu %(protocol)s-adresu."

msgid "IPv4"
msgstr "IPv4"

msgid "IPv6"
msgstr "IPv6"

msgid "IPv4 or IPv6"
msgstr "IPv4 abo IPv6"

msgid "Enter only digits separated by commas."
msgstr "Zapódajśo jano cyfry źělone pśez komy."

#, python-format
msgid "Ensure this value is %(limit_value)s (it is %(show_value)s)."
msgstr "Zawěsććo toś tu gódnotu jo %(limit_value)s (jo %(show_value)s)."

#, python-format
msgid "Ensure this value is less than or equal to %(limit_value)s."
msgstr ""
"Zawěsććo, až toś ta gódnota jo mjeńša ako abo to samske ako %(limit_value)s."

#, python-format
msgid "Ensure this value is greater than or equal to %(limit_value)s."
msgstr ""
"Zawěsććo, až toś ta gódnota jo wětša ako abo to samske ako %(limit_value)s."

#, python-format
msgid "Ensure this value is a multiple of step size %(limit_value)s."
msgstr ""
"Zawěsććo, až toś gódnota jo wjelesere kšacoweje wjelikosći %(limit_value)s."

#, python-format
msgid ""
"Ensure this value is a multiple of step size %(limit_value)s, starting from "
"%(offset)s, e.g. %(offset)s, %(valid_value1)s, %(valid_value2)s, and so on."
msgstr ""
"Zawěsććo, až toś ta gódnota jo wjele wót kšacoweje wjelikosći "
"%(limit_value)s, zachopinajucy z %(offset)s, na pś. %(offset)s, "
"%(valid_value1)s, %(valid_value2)s a tak dalej."

#, python-format
msgid ""
"Ensure this value has at least %(limit_value)d character (it has "
"%(show_value)d)."
msgid_plural ""
"Ensure this value has at least %(limit_value)d characters (it has "
"%(show_value)d)."
msgstr[0] ""
"Zawěsććo, až toś ta gódnota ma nanejmjenjej %(limit_value)d znamuško (ma  "
"%(show_value)d)."
msgstr[1] ""
"Zawěsććo, až toś ta gódnota ma nanejmjenjej %(limit_value)d znamušce (ma  "
"%(show_value)d)."
msgstr[2] ""
"Zawěsććo, až toś ta gódnota ma nanejmjenjej %(limit_value)d znamuška (ma  "
"%(show_value)d)."
msgstr[3] ""
"Zawěsććo, až toś ta gódnota ma nanejmjenjej %(limit_value)d znamuškow (ma  "
"%(show_value)d)."

#, python-format
msgid ""
"Ensure this value has at most %(limit_value)d character (it has "
"%(show_value)d)."
msgid_plural ""
"Ensure this value has at most %(limit_value)d characters (it has "
"%(show_value)d)."
msgstr[0] ""
"Zawěććo, až toś ta gódnota ma maksimalnje %(limit_value)d znamuško (ma "
"%(show_value)d)."
msgstr[1] ""
"Zawěććo, až toś ta gódnota ma maksimalnje %(limit_value)d znamušce (ma "
"%(show_value)d)."
msgstr[2] ""
"Zawěććo, až toś ta gódnota ma maksimalnje %(limit_value)d znamuška (ma "
"%(show_value)d)."
msgstr[3] ""
"Zawěććo, až toś ta gódnota ma maksimalnje %(limit_value)d znamuškow (ma "
"%(show_value)d)."

msgid "Enter a number."
msgstr "Zapódajśo licbu."

#, python-format
msgid "Ensure that there are no more than %(max)s digit in total."
msgid_plural "Ensure that there are no more than %(max)s digits in total."
msgstr[0] "Zawěsććo, až njejo wěcej ako %(max)s cyfry dogromady."
msgstr[1] "Zawěsććo, až njejo wěcej ako %(max)s cyfrowu dogromady."
msgstr[2] "Zawěsććo, až njejo wěcej ako %(max)s cyfrow dogromady."
msgstr[3] "Zawěsććo, až njejo wěcej ako %(max)s cyfrow dogromady."

#, python-format
msgid "Ensure that there are no more than %(max)s decimal place."
msgid_plural "Ensure that there are no more than %(max)s decimal places."
msgstr[0] "Zawěsććo, až njejo wěcej ako %(max)s decimalnego městna."
msgstr[1] "Zawěsććo, až njejo wěcej ako %(max)s decimalneju městnowu."
msgstr[2] "Zawěsććo, až njejo wěcej ako %(max)s decimalnych městnow."
msgstr[3] "Zawěsććo, až njejo wěcej ako %(max)s decimalnych městnow."

#, python-format
msgid ""
"Ensure that there are no more than %(max)s digit before the decimal point."
msgid_plural ""
"Ensure that there are no more than %(max)s digits before the decimal point."
msgstr[0] "Zawěsććo, až njejo wěcej ako %(max)s cyfry pśed decimalneju komu."
msgstr[1] "Zawěsććo, až njejo wěcej ako %(max)s cyfrowu pśed decimalneju komu."
msgstr[2] "Zawěsććo, až njejo wěcej ako %(max)s cyfrow pśed decimalneju komu."
msgstr[3] "Zawěsććo, až njejo wěcej ako %(max)s cyfrow pśed decimalneju komu."

#, python-format
msgid ""
"File extension “%(extension)s” is not allowed. Allowed extensions are: "
"%(allowed_extensions)s."
msgstr ""
"Datajowy sufiks „%(extension)s“ njejo dowólony. Dowólone sufikse su: "
"%(allowed_extensions)s."

msgid "Null characters are not allowed."
msgstr "Znamuška nul njejsu dowólone."

msgid "and"
msgstr "a"

#, python-format
msgid "%(model_name)s with this %(field_labels)s already exists."
msgstr "%(model_name)s z toś tym %(field_labels)s južo eksistěrujo."

#, python-format
msgid "Constraint “%(name)s” is violated."
msgstr "Wobranicowanje \"%(name)s\" jo pśestupjone."

#, python-format
msgid "Value %(value)r is not a valid choice."
msgstr "Gódnota %(value)r njejo płaśiwa wóleńska móžnosć."

msgid "This field cannot be null."
msgstr "Toś to pólo njamóžo nul byś."

msgid "This field cannot be blank."
msgstr "Toś to pólo njamóžo prozne byś."

#, python-format
msgid "%(model_name)s with this %(field_label)s already exists."
msgstr "%(model_name)s z toś tym %(field_label)s južo eksistěrujo."

#. Translators: The 'lookup_type' is one of 'date', 'year' or
#. 'month'. Eg: "Title must be unique for pub_date year"
#, python-format
msgid ""
"%(field_label)s must be unique for %(date_field_label)s %(lookup_type)s."
msgstr ""
"%(field_label)s musy za %(date_field_label)s %(lookup_type)s jadnorazowy byś."

#, python-format
msgid "Field of type: %(field_type)s"
msgstr "Typ póla: %(field_type)s"

#, python-format
msgid "“%(value)s” value must be either True or False."
msgstr "Gódnota „%(value)s“ musy pak True pak False byś."

#, python-format
msgid "“%(value)s” value must be either True, False, or None."
msgstr "Gódnota „%(value)s“ musy pak True, False pak None byś."

msgid "Boolean (Either True or False)"
msgstr "Boolean (pak True pak False)"

#, python-format
msgid "String (up to %(max_length)s)"
msgstr "Znamuškowy rjeśazk (až %(max_length)s)"

msgid "String (unlimited)"
msgstr "Znamuškowy rjeśazk (njewobgranicowany)"

msgid "Comma-separated integers"
msgstr "Pśez komu źělone cełe licby"

#, python-format
msgid ""
"“%(value)s” value has an invalid date format. It must be in YYYY-MM-DD "
"format."
msgstr ""
"Gódnota „%(value)s“ ma njepłaśiwy datumowy format. Musy we formaśe DD.MM."
"YYYY byś."

#, python-format
msgid ""
"“%(value)s” value has the correct format (YYYY-MM-DD) but it is an invalid "
"date."
msgstr ""
"Gódnota „%(value)s“ ma korektny format (DD.MM.YYYY), ale jo njepłaśiwy datum."

msgid "Date (without time)"
msgstr "Datum (bźez casa)"

#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[."
"uuuuuu]][TZ] format."
msgstr ""
"Gódnota „%(value)s“ ma njepłaśiwy format. Musy w formaśe DD.MM.YYYY HH:MM[:"
"ss[.uuuuuu]][TZ] byś."

#, python-format
msgid ""
"“%(value)s” value has the correct format (YYYY-MM-DD HH:MM[:ss[.uuuuuu]]"
"[TZ]) but it is an invalid date/time."
msgstr ""
"Gódnota „%(value)s“ ma korektny format (DD.MM.YYYY HH:MM[:ss[.uuuuuu]][TZ]), "
"ale jo njepłaśiwy datum/cas."

msgid "Date (with time)"
msgstr "Datum (z casom)"

#, python-format
msgid "“%(value)s” value must be a decimal number."
msgstr "Gódnota „%(value)s“ musy decimalna licba byś."

msgid "Decimal number"
msgstr "Decimalna licba"

#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in [DD] [[HH:]MM:]ss[."
"uuuuuu] format."
msgstr ""
"Gódnota „%(value)s“ ma njepłaśiwy format. Musy we formaśe  [DD] "
"[[HH:]MM:]ss[.uuuuuu] byś."

msgid "Duration"
msgstr "Traśe"

msgid "Email address"
msgstr "E-mailowa adresa"

msgid "File path"
msgstr "Datajowa sćažka"

#, python-format
msgid "“%(value)s” value must be a float."
msgstr "Gódnota „%(value)s“ musy typ float měś."

msgid "Floating point number"
msgstr "Licba běžeceje komy"

#, python-format
msgid "“%(value)s” value must be an integer."
msgstr "Gódnota „%(value)s“ musy ceła licba byś."

msgid "Integer"
msgstr "Integer"

msgid "Big (8 byte) integer"
msgstr "Big (8 bajtow) integer"

msgid "Small integer"
msgstr "Mała ceła licba"

msgid "IPv4 address"
msgstr "IPv4-adresa"

msgid "IP address"
msgstr "IP-adresa"

#, python-format
msgid "“%(value)s” value must be either None, True or False."
msgstr "Gódnota „%(value)s“ musy pak None, True pak False byś."

msgid "Boolean (Either True, False or None)"
msgstr "Boolean (pak True, False pak None)"

msgid "Positive big integer"
msgstr "Pozitiwna wjelika ceła licba"

msgid "Positive integer"
msgstr "Pozitiwna ceła licba"

msgid "Positive small integer"
msgstr "Pozitiwna mała ceła licba"

#, python-format
msgid "Slug (up to %(max_length)s)"
msgstr "Adresowe mě (až %(max_length)s)"

msgid "Text"
msgstr "Tekst"

#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in HH:MM[:ss[.uuuuuu]] "
"format."
msgstr ""
"Gódnota „%(value)s“  ma njepłaśiwy format. Musy w formaśe HH:MM[:ss[."
"uuuuuu]] byś."

#, python-format
msgid ""
"“%(value)s” value has the correct format (HH:MM[:ss[.uuuuuu]]) but it is an "
"invalid time."
msgstr ""
"Gódnota „%(value)s“ ma korektny format (HH:MM[:ss[.uuuuuu]]), ale jo "
"njepłaśiwy cas."

msgid "Time"
msgstr "Cas"

msgid "URL"
msgstr "URL"

msgid "Raw binary data"
msgstr "Gropne binarne daty"

#, python-format
msgid "“%(value)s” is not a valid UUID."
msgstr "„%(value)s“ njejo płaśiwy UUID."

msgid "Universally unique identifier"
msgstr "Uniwerselnje jadnorazowy identifikator"

msgid "File"
msgstr "Dataja"

msgid "Image"
msgstr "Woraz"

msgid "A JSON object"
msgstr "JSON-objekt"

msgid "Value must be valid JSON."
msgstr "Gódnota musy płaśiwy JSON byś."

#, python-format
msgid "%(model)s instance with %(field)s %(value)r is not a valid choice."
msgstr "Instanca %(model)s z  %(field)s %(value)r njejo płaśiwa wólba."

msgid "Foreign Key (type determined by related field)"
msgstr "Cuzy kluc (typ póstaja se pśez wótpowědne pólo)"

msgid "One-to-one relationship"
msgstr "Póśěg jaden jaden"

#, python-format
msgid "%(from)s-%(to)s relationship"
msgstr "Póśěg %(from)s-%(to)s"

#, python-format
msgid "%(from)s-%(to)s relationships"
msgstr "Póśěgi %(from)s-%(to)s"

msgid "Many-to-many relationship"
msgstr "Póśěg wjele wjele"

#. Translators: If found as last label character, these punctuation
#. characters will prevent the default label_suffix to be appended to the
#. label
msgid ":?.!"
msgstr ":?.!"

msgid "This field is required."
msgstr "Toś to pólo jo trěbne."

msgid "Enter a whole number."
msgstr "Zapódajśo cełu licbu."

msgid "Enter a valid date."
msgstr "Zapódajśo płaśiwy datum."

msgid "Enter a valid time."
msgstr "Zapódajśo płaśiwy cas."

msgid "Enter a valid date/time."
msgstr "Zapódajśo płaśiwy datum/cas."

msgid "Enter a valid duration."
msgstr "Zapódaśe płaśiwe traśe."

#, python-brace-format
msgid "The number of days must be between {min_days} and {max_days}."
msgstr "Licba dnjow musy mjazy  {min_days} a {max_days} byś."

msgid "No file was submitted. Check the encoding type on the form."
msgstr ""
"Dataja njejo se wótpósłała. Pśeglědujśo koděrowański typ na formularje. "

msgid "No file was submitted."
msgstr "Žedna dataja jo se wótpósłała."

msgid "The submitted file is empty."
msgstr "Wótpósłana dataja jo prozna."

#, python-format
msgid "Ensure this filename has at most %(max)d character (it has %(length)d)."
msgid_plural ""
"Ensure this filename has at most %(max)d characters (it has %(length)d)."
msgstr[0] ""
"Zawěsććo, až toś to datajowe mě ma maksimalnje %(max)d znamuško (ma "
"%(length)d)."
msgstr[1] ""
"Zawěsććo, až toś to datajowe mě ma maksimalnje %(max)d znamušce (ma "
"%(length)d)."
msgstr[2] ""
"Zawěsććo, až toś to datajowe mě ma maksimalnje %(max)d znamuška (ma "
"%(length)d)."
msgstr[3] ""
"Zawěsććo, až toś to datajowe mě ma maksimalnje %(max)d znamuškow (ma "
"%(length)d)."

msgid "Please either submit a file or check the clear checkbox, not both."
msgstr ""
"Pšosym pak wótpósćelśo dataju pak stajśo kokulku do kontrolnego kašćika, "
"njecyńśo wobej."

msgid ""
"Upload a valid image. The file you uploaded was either not an image or a "
"corrupted image."
msgstr ""
"Nagrajśo płaśiwy wobraz. Dataja, kótaruž sćo nagrał, pak njejo wobraz był "
"pak jo wobškóźony wobraz."

#, python-format
msgid "Select a valid choice. %(value)s is not one of the available choices."
msgstr ""
"Wubjeŕśo płaśiwu wóleńsku móžnosć. %(value)s njejo jadna z k dispoziciji "
"stojecych wóleńskich móžnosćow."

msgid "Enter a list of values."
msgstr "Zapódajśo lisćinu gódnotow."

msgid "Enter a complete value."
msgstr "Zapódajśo dopołnu gódnotu."

msgid "Enter a valid UUID."
msgstr "Zapódajśo płaśiwy UUID."

msgid "Enter a valid JSON."
msgstr "Zapódajśo płaśiwy JSON."

#. Translators: This is the default suffix added to form field labels
msgid ":"
msgstr ":"

#, python-format
msgid "(Hidden field %(name)s) %(error)s"
msgstr "(Schowane pólo %(name)s) %(error)s"

#, python-format
msgid ""
"ManagementForm data is missing or has been tampered with. Missing fields: "
"%(field_names)s. You may need to file a bug report if the issue persists."
msgstr ""
"Daty ManagementForm feluju abo su wobškóźone. Felujuce póla: "
"%(field_names)s. Móžośo zmólkowu rozpšawu pisaś, jolic problem dalej "
"eksistěrujo."

#, python-format
msgid "Please submit at most %(num)d form."
msgid_plural "Please submit at most %(num)d forms."
msgstr[0] "Pšosym wótposćelśo maksimalnje %(num)d formular."
msgstr[1] "Pšosym wótposćelśo maksimalnje %(num)d formulara."
msgstr[2] "Pšosym wótposćelśo maksimalnje %(num)d formulary."
msgstr[3] "Pšosym wótposćelśo maksimalnje %(num)d formularow."

#, python-format
msgid "Please submit at least %(num)d form."
msgid_plural "Please submit at least %(num)d forms."
msgstr[0] "Pšosym wótposćelśo minimalnje %(num)d formular."
msgstr[1] "Pšosym wótposćelśo minimalnje %(num)d formulara."
msgstr[2] "Pšosym wótposćelśo minimalnje %(num)d formulary."
msgstr[3] "Pšosym wótposćelśo minimalnje %(num)d formularow."

msgid "Order"
msgstr "Rěd"

msgid "Delete"
msgstr "Lašowaś"

#, python-format
msgid "Please correct the duplicate data for %(field)s."
msgstr "Pšosym korigěrujśo dwójne daty za %(field)s."

#, python-format
msgid "Please correct the duplicate data for %(field)s, which must be unique."
msgstr ""
"Pšosym korigěrujśo dwójne daty za %(field)s, kótarež muse jadnorazowe byś."

#, python-format
msgid ""
"Please correct the duplicate data for %(field_name)s which must be unique "
"for the %(lookup)s in %(date_field)s."
msgstr ""
"Pšosym korigěrujśo dwójne daty za %(field_name)s, kótarež muse za %(lookup)s "
"w %(date_field)s jadnorazowe byś."

msgid "Please correct the duplicate values below."
msgstr "Pšosym korigěrujśo slědujuce dwójne gódnoty."

msgid "The inline value did not match the parent instance."
msgstr "Gódnota inline nadrědowanej instance njewótpowědujo."

msgid "Select a valid choice. That choice is not one of the available choices."
msgstr ""
"Wubjeŕśo płaśiwu wóleńsku móžnosć. Toś ta wóleńska móžnosć njejo žedna z "
"wóleńskich móžnosćow."

#, python-format
msgid "“%(pk)s” is not a valid value."
msgstr "„%(pk)s“ njejo płaśiwa gódnota."

#, python-format
msgid ""
"%(datetime)s couldn’t be interpreted in time zone %(current_timezone)s; it "
"may be ambiguous or it may not exist."
msgstr ""
"%(datetime)s njedajo se w casowej conje %(current_timezone)s "
"interpretěrowaś; jo dwójozmysłowy abo snaź njeeksistěrujo."

msgid "Clear"
msgstr "Lašowaś"

msgid "Currently"
msgstr "Tuchylu"

msgid "Change"
msgstr "Změniś"

msgid "Unknown"
msgstr "Njeznaty"

msgid "Yes"
msgstr "Jo"

msgid "No"
msgstr "Ně"

#. Translators: Please do not add spaces around commas.
msgid "yes,no,maybe"
msgstr "jo,ně,snaź"

#, python-format
msgid "%(size)d byte"
msgid_plural "%(size)d bytes"
msgstr[0] "%(size)d bajt"
msgstr[1] "%(size)d bajta"
msgstr[2] "%(size)d bajty"
msgstr[3] "%(size)d bajtow"

#, python-format
msgid "%s KB"
msgstr "%s KB"

#, python-format
msgid "%s MB"
msgstr "%s MB"

#, python-format
msgid "%s GB"
msgstr "%s GB"

#, python-format
msgid "%s TB"
msgstr "%s TB"

#, python-format
msgid "%s PB"
msgstr "%s PB"

msgid "p.m."
msgstr "wótpołdnja"

msgid "a.m."
msgstr "dopołdnja"

msgid "PM"
msgstr "wótpołdnja"

msgid "AM"
msgstr "dopołdnja"

msgid "midnight"
msgstr "połnoc"

msgid "noon"
msgstr "połdnjo"

msgid "Monday"
msgstr "Pónjeźele"

msgid "Tuesday"
msgstr "Wałtora"

msgid "Wednesday"
msgstr "Srjoda"

msgid "Thursday"
msgstr "Stwórtk"

msgid "Friday"
msgstr "Pětk"

msgid "Saturday"
msgstr "Sobota"

msgid "Sunday"
msgstr "Njeźela"

msgid "Mon"
msgstr "Pón"

msgid "Tue"
msgstr "Wał"

msgid "Wed"
msgstr "Srj"

msgid "Thu"
msgstr "Stw"

msgid "Fri"
msgstr "Pět"

msgid "Sat"
msgstr "Sob"

msgid "Sun"
msgstr "Nje"

msgid "January"
msgstr "Januar"

msgid "February"
msgstr "Februar"

msgid "March"
msgstr "Měrc"

msgid "April"
msgstr "Apryl"

msgid "May"
msgstr "Maj"

msgid "June"
msgstr "Junij"

msgid "July"
msgstr "Julij"

msgid "August"
msgstr "Awgust"

msgid "September"
msgstr "September"

msgid "October"
msgstr "Oktober"

msgid "November"
msgstr "Nowember"

msgid "December"
msgstr "December"

msgid "jan"
msgstr "jan"

msgid "feb"
msgstr "feb"

msgid "mar"
msgstr "měr"

msgid "apr"
msgstr "apr"

msgid "may"
msgstr "maj"

msgid "jun"
msgstr "jun"

msgid "jul"
msgstr "jul"

msgid "aug"
msgstr "awg"

msgid "sep"
msgstr "sep"

msgid "oct"
msgstr "okt"

msgid "nov"
msgstr "now"

msgid "dec"
msgstr "dec"

msgctxt "abbrev. month"
msgid "Jan."
msgstr "Jan."

msgctxt "abbrev. month"
msgid "Feb."
msgstr "Feb."

msgctxt "abbrev. month"
msgid "March"
msgstr "Měrc"

msgctxt "abbrev. month"
msgid "April"
msgstr "Apryl"

msgctxt "abbrev. month"
msgid "May"
msgstr "Maj"

msgctxt "abbrev. month"
msgid "June"
msgstr "Junij"

msgctxt "abbrev. month"
msgid "July"
msgstr "Julij"

msgctxt "abbrev. month"
msgid "Aug."
msgstr "Awg."

msgctxt "abbrev. month"
msgid "Sept."
msgstr "Sept."

msgctxt "abbrev. month"
msgid "Oct."
msgstr "Okt."

msgctxt "abbrev. month"
msgid "Nov."
msgstr "Now."

msgctxt "abbrev. month"
msgid "Dec."
msgstr "Dec."

msgctxt "alt. month"
msgid "January"
msgstr "Januar"

msgctxt "alt. month"
msgid "February"
msgstr "Februar"

msgctxt "alt. month"
msgid "March"
msgstr "Měrc"

msgctxt "alt. month"
msgid "April"
msgstr "Apryl"

msgctxt "alt. month"
msgid "May"
msgstr "Maj"

msgctxt "alt. month"
msgid "June"
msgstr "Junij"

msgctxt "alt. month"
msgid "July"
msgstr "Julij"

msgctxt "alt. month"
msgid "August"
msgstr "Awgust"

msgctxt "alt. month"
msgid "September"
msgstr "September"

msgctxt "alt. month"
msgid "October"
msgstr "Oktober"

msgctxt "alt. month"
msgid "November"
msgstr "Nowember"

msgctxt "alt. month"
msgid "December"
msgstr "December"

msgid "This is not a valid IPv6 address."
msgstr "To njejo płaśiwa IPv6-adresa."

#, python-format
msgctxt "String to return when truncating text"
msgid "%(truncated_text)s…"
msgstr "%(truncated_text)s…"

msgid "or"
msgstr "abo"

#. Translators: This string is used as a separator between list elements
msgid ", "
msgstr ", "

#, python-format
msgid "%(num)d year"
msgid_plural "%(num)d years"
msgstr[0] "%(num)d lěto"
msgstr[1] "%(num)d lěśe"
msgstr[2] "%(num)d lěta"
msgstr[3] "%(num)d lět"

#, python-format
msgid "%(num)d month"
msgid_plural "%(num)d months"
msgstr[0] "%(num)d mjasec"
msgstr[1] "%(num)d mjaseca"
msgstr[2] "%(num)d mjasece"
msgstr[3] "%(num)dmjasecow"

#, python-format
msgid "%(num)d week"
msgid_plural "%(num)d weeks"
msgstr[0] "%(num)d tyźeń"
msgstr[1] "%(num)d tyźenja"
msgstr[2] "%(num)d tyźenje"
msgstr[3] "%(num)d tyźenjow"

#, python-format
msgid "%(num)d day"
msgid_plural "%(num)d days"
msgstr[0] "%(num)d źeń "
msgstr[1] "%(num)d dnja"
msgstr[2] "%(num)d dny"
msgstr[3] "%(num)d dnjow"

#, python-format
msgid "%(num)d hour"
msgid_plural "%(num)d hours"
msgstr[0] "%(num)d góźina"
msgstr[1] "%(num)d góźinje"
msgstr[2] "%(num)d góźiny"
msgstr[3] "%(num)d góźin"

#, python-format
msgid "%(num)d minute"
msgid_plural "%(num)d minutes"
msgstr[0] "%(num)d minuta"
msgstr[1] "%(num)d minuśe"
msgstr[2] "%(num)d minuty"
msgstr[3] "%(num)d minutow"

msgid "Forbidden"
msgstr "Zakazany"

msgid "CSRF verification failed. Request aborted."
msgstr "CSRF-pśeglědanje njejo se raźiło. Napšašowanje jo se pśetergnuło."

msgid ""
"You are seeing this message because this HTTPS site requires a “Referer "
"header” to be sent by your web browser, but none was sent. This header is "
"required for security reasons, to ensure that your browser is not being "
"hijacked by third parties."
msgstr ""
"Wiźiśo toś tu powěźeńku, dokulaž toś to HTTPS-sedło trjeba \"Referer "
"header\", aby se pśez waš webwobglědowak słało, ale žedna njejo se pósłała. "
"Toś ta głowa jo trěbna z pśicynow wěstoty, aby so zawěsćiło, až waš "
"wobglědowak njekaprujo se wót tśeśich."

msgid ""
"If you have configured your browser to disable “Referer” headers, please re-"
"enable them, at least for this site, or for HTTPS connections, or for “same-"
"origin” requests."
msgstr ""
"Jolic sćo swój wobglědowak tak konfigurěrował, aby se głowy 'Referer' "
"znjemóžnili, zmóžniśo je pšosym zasej, nanejmjenjej za toś to sedło, za "
"HTTPS-zwiski abo za napšašowanja 'same-origin'."

msgid ""
"If you are using the <meta name=\"referrer\" content=\"no-referrer\"> tag or "
"including the “Referrer-Policy: no-referrer” header, please remove them. The "
"CSRF protection requires the “Referer” header to do strict referer checking. "
"If you’re concerned about privacy, use alternatives like <a "
"rel=\"noreferrer\" …> for links to third-party sites."
msgstr ""
"Jolic woznamjenje <meta name=\"referrer\" content=\"no-referrer\"> wužywaśo "
"abo głowu „Referrer-Policy: no-referrer“ zapśimujośo, wótwónoźćo je. CSRF-"
"šćit pomina se głowu „Referer“, aby striktnu kontrolu referera pśewjasć. "
"Jolic se wó swóju priwatnosć staraśo, wužywajśo alternatiwy ako <a "
"rel=\"noreferrer\" …> za wótkazy k sedłam tśeśich."

msgid ""
"You are seeing this message because this site requires a CSRF cookie when "
"submitting forms. This cookie is required for security reasons, to ensure "
"that your browser is not being hijacked by third parties."
msgstr ""
"Wiźiśo toś tu powěźeńku, dokulaž toś to HTTPS-sedło trjeba CSRF-cookie, aby "
"formulary wótpósłało. Toś ten cookie jo trěbna z pśicynow wěstoty, aby so "
"zawěsćiło, až waš wobglědowak njekaprujo se wót tśeśich."

msgid ""
"If you have configured your browser to disable cookies, please re-enable "
"them, at least for this site, or for “same-origin” requests."
msgstr ""
"Jolic sćo swój wobglědowak tak konfigurěrował, aby cookieje znjemóžnili, "
"zmóžniśo je pšosym zasej, nanejmjenjej za toś to sedło abo za napšašowanja "
"„same-origin“."

msgid "More information is available with DEBUG=True."
msgstr "Dalšne informacije su k dispoziciji  z DEBUG=True."

msgid "No year specified"
msgstr "Žedno lěto pódane"

msgid "Date out of range"
msgstr "Datum zwenka wobcerka"

msgid "No month specified"
msgstr "Žeden mjasec pódany"

msgid "No day specified"
msgstr "Žeden źeń pódany"

msgid "No week specified"
msgstr "Žeden tyźeń pódany"

#, python-format
msgid "No %(verbose_name_plural)s available"
msgstr "Žedne %(verbose_name_plural)s k dispoziciji"

#, python-format
msgid ""
"Future %(verbose_name_plural)s not available because %(class_name)s."
"allow_future is False."
msgstr ""
"Pśichodne %(verbose_name_plural)s njejo k dispoziciji, dokulaž "
"%(class_name)s.allow_future jo False."

#, python-format
msgid "Invalid date string “%(datestr)s” given format “%(format)s”"
msgstr ""
"Njepłaśiwy „%(format)s“ za datumowy znamuškowy rjeśazk „%(datestr)s“ pódany"

#, python-format
msgid "No %(verbose_name)s found matching the query"
msgstr "Žedno %(verbose_name)s namakane, kótarež wótpowědujo napšašowanjeju."

msgid "Page is not “last”, nor can it be converted to an int."
msgstr "Bok njejo „last“, ani njedajo se do „int“ konwertěrowaś."

#, python-format
msgid "Invalid page (%(page_number)s): %(message)s"
msgstr "Njepłaśiwy bok (%(page_number)s): %(message)s"

#, python-format
msgid "Empty list and “%(class_name)s.allow_empty” is False."
msgstr "Prozna lisćina a „%(class_name)s.allow_empty“ jo False."

msgid "Directory indexes are not allowed here."
msgstr "Zapisowe indekse njejsu how dowólone."

#, python-format
msgid "“%(path)s” does not exist"
msgstr "„%(path)s“ njeeksistěrujo"

#, python-format
msgid "Index of %(directory)s"
msgstr "Indeks %(directory)s"

msgid "The install worked successfully! Congratulations!"
msgstr "Instalacija jo była wuspěšna! Gratulacija!"

#, python-format
msgid ""
"View <a href=\"https://docs.djangoproject.com/en/%(version)s/releases/\" "
"target=\"_blank\" rel=\"noopener\">release notes</a> for Django %(version)s"
msgstr ""
"<a href=\"https://docs.djangoproject.com/en/%(version)s/releases/\" "
"target=\"_blank\" rel=\"noopener\">Wersijowe informacije</a> za Django "
"%(version)s pokazaś"

#, python-format
msgid ""
"You are seeing this page because <a href=\"https://docs.djangoproject.com/en/"
"%(version)s/ref/settings/#debug\" target=\"_blank\" "
"rel=\"noopener\">DEBUG=True</a> is in your settings file and you have not "
"configured any URLs."
msgstr ""
"Wiźiśo toś ten bok, dokulaž <a href=\"https://docs.djangoproject.com/en/"
"%(version)s/ref/settings/#debug\" target=\"_blank\" "
"rel=\"noopener\">DEBUG=True</a> jo w swójej dataji nastajenjow a njejsćo "
"konfigurěrował URL."

msgid "Django Documentation"
msgstr "Dokumentacija Django"

msgid "Topics, references, &amp; how-to’s"
msgstr "Temy, reference a rozpokazanja"

msgid "Tutorial: A Polling App"
msgstr "Rozpokazanje: Napšašowańske nałoženje"

msgid "Get started with Django"
msgstr "Prědne kšace z Django"

msgid "Django Community"
msgstr "Zgromaźeństwo Django"

msgid "Connect, get help, or contribute"
msgstr "Zwězajśo, wobsarajśo se pomoc abo źěłajśo sobu"
