from ar.tests import *
from at.tests import *
from au.tests import *
from be.tests import *
from br.tests import *
from ca.tests import *
from ch.tests import *
from cl.tests import *
from cn.tests import *
from co.tests import *
from cz.tests import *
from de.tests import *
from ec.tests import *
from es.tests import *
from fi.tests import *
from fr.tests import *
from gb.tests import *
from generic.tests import *
from hr.tests import *
from id.tests import *
from ie.tests import *
from il.tests import *
from in_.tests import *
from is_.tests import *
from it.tests import *
from jp.tests import *
from kw.tests import *
from mk.tests import *
from mx.tests import *
from nl.tests import *
from pl.tests import *
from pt.tests import *
from py.tests import *
from ro.tests import *
from ru.tests import *
from se.tests import *
from si.tests import *
from sk.tests import *
from tr.tests import *
from us.tests import *
from uy.tests import *
from za.tests import *
