# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160101171725 on 2016-01-02 14:53
from __future__ import unicode_literals

import os

from django.db import connection, migrations, models


def add_database_triggers(apps, schema_editor):

    sql_file = None
    if connection.vendor == 'postgresql':
        sql_file = 'postgresql_triggers.sql'
    elif connection.vendor == 'oracle':
        sql_file = 'oracle_triggers.sql'

    if sql_file:
        model = apps.get_model('delegated_fields', 'DelegatedWithDBDefault')
        cursor = connection.cursor()
        current_dir = os.path.dirname(os.path.realpath(__file__))
        sql_file = os.path.join(current_dir, sql_file)
        sql = open(sql_file, 'r').read().format(table_name=model._meta.db_table)
        cursor.execute(sql)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegatedWithDBDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('now', models.DateTimeField(delegate=True,
                 delegate_on_insert=True, delegate_on_update=True,
                 return_on_insert=True, return_on_update=True)),
                ('num', models.IntegerField(return_on_insert=True,
                 return_on_update=True)),
                ('num_a', models.IntegerField(return_on_insert=True)),
                ('num_b', models.IntegerField(return_on_update=True)),
                ('b', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlyDelegatedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('a', models.TextField(delegate=True, delegate_on_insert=True,
                 delegate_on_update=True, null=True, return_on_insert=True,
                 return_on_update=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartiallyDelegated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('insert', models.IntegerField(delegate_on_insert=True,
                 null=True, return_on_insert=True)),
                ('update', models.IntegerField(delegate_on_update=True,
                 null=True, return_on_update=True)),
                ('both', models.IntegerField(delegate=True,
                 delegate_on_insert=True, delegate_on_update=True, null=True,
                 return_on_insert=True, return_on_update=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithDelegatedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('a', models.TextField(delegate=True, delegate_on_insert=True,
                 delegate_on_update=True, null=True, return_on_insert=True,
                 return_on_update=True)),
                ('b', models.TextField(null=True)),
            ],
        ),
        migrations.RunPython(add_database_triggers),
    ]
