# Generated by Django 4.1.dev20220516064334 on 2022-05-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migrations", "0003_alter_mymodel2_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel1",
            name="field_1",
        ),
        migrations.AddField(
            model_name="mymodel1",
            name="field_3",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mymodel1",
            name="field_4",
            field=models.IntegerField(null=True),
        ),
    ]
