# Configuration for the Read The Docs (RTD) builds of the documentation.
# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
# The python.install.requirements pins the version of Sphinx used.
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt

formats: all
