# Configuration for the Read The Docs (RTD) builds of the documentation.
# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
# The python.install.requirements pins the version of Sphinx used.
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_build:
      # RTD's htmlzip uses the singlehtml sphinx builder which just generates
      # a single giant HTML file. So we build our own zip instead based on the
      # regular HTML builder.
      - mkdir -p $READTHEDOCS_OUTPUT/htmlzip
      - cd $READTHEDOCS_OUTPUT/html
      - zip -r $READTHEDOCS_OUTPUT/htmlzip/$READTHEDOCS_PROJECT.zip . -x '_sources/*' .buildinfo objects.inv

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt

# htmlzip is built manually in post_build
formats:
  - epub
  - pdf
