# /// script
# dependencies = [
#   "beautifulsoup4>=4",
#   "httpx",
# ]
# ///

"""
Script to extract pyupgrade (UP) rules from Ruff documentation.

Can be run via
> uv run scrape_pyupgrade_rules.py

The code in this file is generated by Claude, then manually improved.
"""

import httpx
from bs4 import BeautifulSoup

RULES_URL = "https://docs.astral.sh/ruff/rules/"


def fetch_ruff_rules() -> list[dict]:
    """
    Fetch and parse Ruff pyupgrade rules from the documentation.

    Returns:
        List of dictionaries containing rule information.
    """
    print(f"Fetching rules from {RULES_URL}...")
    response = httpx.get(RULES_URL)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")

    # Find the pyupgrade section
    pyupgrade_section = soup.find("h2", id="pyupgrade-up")
    if not pyupgrade_section:
        raise ValueError("Could not find pyupgrade section")

    # Find the table after the pyupgrade heading
    table = pyupgrade_section.find_next("table")
    if not table:
        raise ValueError("Could not find rules table")

    rules = []

    # Parse table rows (skip header)
    rows = table.find("tbody").find_all("tr")

    for row in rows:
        cols = row.find_all("td")
        if len(cols) >= 3:
            code = cols[0].get_text(strip=True)
            name = cols[1].get_text(strip=True)
            message = cols[2].get_text(strip=True)

            # Check for symbols in the last column
            symbols = cols[3].get_text(strip=True) if len(cols) > 3 else ""

            is_preview = "🧪" in symbols
            is_deprecated = "⚠️" in symbols
            is_removed = "❌" in symbols
            is_fixable = "🛠️" in symbols

            rules.append(
                {
                    "code": code,
                    "name": name,
                    "message": message,
                    "is_preview": is_preview,
                    "is_deprecated": is_deprecated,
                    "is_removed": is_removed,
                    "is_fixable": is_fixable,
                }
            )

    return rules


def generate_toml_config(rules: list[dict], include_removed: bool = False) -> str:
    """
    Generate TOML configuration string from rules.

    Args:
        rules: List of rule dictionaries
        include_removed: Whether to include removed rules (commented out)

    Returns:
        TOML configuration string
    """
    lines = ["[lint]", "select = ["]

    for rule in rules:
        comment_parts = []

        # Add status indicators
        if rule["is_removed"]:
            if not include_removed:
                continue
            comment_parts.append("REMOVED")
        if rule["is_deprecated"]:
            comment_parts.append("DEPRECATED")
        if rule["is_preview"]:
            comment_parts.append("preview")

        # Build comment
        comment = f"{rule['name']}"
        if comment_parts:
            comment += f" ({', '.join(comment_parts)})"

        # Add the rule line
        prefix = "# " if rule["is_removed"] else ""
        lines.append(f'    {prefix}"{rule["code"]}",  # {comment}')

    lines.append("]")

    return "\n".join(lines)


def print_summary(rules: list[dict]) -> None:
    total = len(rules)
    preview = sum(1 for r in rules if r["is_preview"])
    deprecated = sum(1 for r in rules if r["is_deprecated"])
    removed = sum(1 for r in rules if r["is_removed"])
    fixable = sum(1 for r in rules if r["is_fixable"])
    active = total - removed

    print("\nSummary:")
    print(f"  Total rules: {total}")
    print(f"  Active rules: {active}")
    print(f"  Removed rules: {removed}")
    print(f"  Preview rules: {preview}")
    print(f"  Deprecated rules: {deprecated}")
    print(f"  Auto-fixable rules: {fixable}")


def main():
    # Fetch rules
    rules = fetch_ruff_rules()

    print(f"Found {len(rules)} pyupgrade rules")

    # Print summary
    print_summary(rules)

    # Generate outputs
    print("\n" + "=" * 60)
    print("TOML Configuration (active rules only):")
    print("=" * 60)
    toml_config = generate_toml_config(rules)
    print(toml_config)


if __name__ == "__main__":
    main()
