"""
Django settings for DJangoTestCases project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's23x!bq=1ppw)4!(oucu!7t85_5r8e-hx18@)ri9frrmq&71=h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

FIXTURE_DIRS = (
      os.path.join(BASE_DIR, "fixtures",),
)

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.redirects',
    'django.contrib.comments',
    'django.templatetags.subpackage.echo',
    'test_runner',
    'django.db.transactions',
    'django.core.servers',
    'fixtures_migration',
    'fixtures_model_package',
    'fixtures_regress',
    'get_or_create',
    'django.db.backends.base.introspection',
    'django.db.migrations',
    'migration_test_data_persistence',
    'select_for_update',
    'django.core.serializers',
    'fixtures_model_package',
    'model_inheritance',
  
)



MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'DJangoTestCases.urls'

BASE_TEST_DIR = os.path.join(BASE_DIR,'tests')

 
TEMPATE_TESTS = os.path.join(BASE_TEST_DIR,'template_tests')
TEMPATE_LODER=os.path.join(BASE_TEST_DIR,'template_loader')
TEMPATE_BACKENDS=os.path.join(BASE_TEST_DIR,'template_backends')
TEST_UTILS=os.path.join(BASE_TEST_DIR,'test_utils')
TEST_CLIENT_REGRESS=os.path.join(BASE_TEST_DIR,'test_client_regress')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DJangoTestCases.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
""" 
DATABASES = {
      'default': {
          'ENGINE'     : 'django.db.backends.mysql',
                'NAME'       : 'sample1',
                'USER'       : 'db2admin',
                'PASSWORD'   : 'db2admin',
                'HOST'       : 'localhost',
                'PORT'       : '3306',
                'PCONNECT'   :  True,      #Optional property, default is false
      },
       
             'other': {
                'ENGINE'     : 'django.db.backends.mysql',
                'NAME'       : 'sample',
                'USER'       : 'db2admin',
                'PASSWORD'   : 'db2admin',
                'HOST'       : 'localhost',
                'PORT'       : '3306',
                'PCONNECT'   :  True,      #Optional property, default is false
            },
   }
   
"""
DATABASES = {
        
      'default':{
                   'ENGINE'     : 'ibm_db_django',
                   'NAME'       : 'sample7',
                   'USER'       : 'db2admin',
                   'PASSWORD'   : 'db2admin',
                   'HOST'       : 'localhost',
                   'PORT'       : '50000',
                   'PCONNECT'   :  True,      #Optional property, default is false
                },
             
        'other': {
         'ENGINE'     : 'ibm_db_django',
         'NAME'       : 'sample3',
         'USER'       : 'db2admin',
         'PASSWORD'   : 'db2admin',
         'HOST'       : 'localhost',
         'PORT'       : '50000',
         'PCONNECT'   :  True,      #Optional property, default is false
      },
             
   
   }
  


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
