DATA_TYPES = {
    'AutoField':                    'number(11)',
    'BooleanField':                 'number(1) CHECK (%(column)s IN (0,1))',
    'CharField':                    'varchar2(%(maxlength)s)',
    'CommaSeparatedIntegerField':   'varchar2(%(maxlength)s)',
    'DateField':                    'date',
    'DateTimeField':                'timestamp with time zone',
    'FileField':                    'varchar2(100)',
    'FilePathField':                'varchar2(100)',
    'FloatField':                   'number(%(max_digits)s, %(decimal_places)s)',
    'ImageField':                   'varchar2(100)',
    'IntegerField':                 'number(11)',
    'IPAddressField':               'char(15)',
    'ManyToManyField':              None,
    'NullBooleanField':             'number(1) CHECK ((%(column)s IN (0,1)) OR (%(column)s IS NULL))',
    'OneToOneField':                'number(11)',
    'PhoneNumberField':             'varchar2(20)',
    'PositiveIntegerField':         'number(11) CHECK (%(column)s >= 0)',
    'PositiveSmallIntegerField':    'number(11) CHECK (%(column)s >= 0)',
    'SlugField':                    'varchar2(50)',
    'SmallIntegerField':            'number(11)',
    'TextField':                    'clob',
    'TimeField':                    'timestamp',
    'URLField':                     'varchar2(200)',
    'USStateField':                 'char(2)',
}
