# Generated by Django 4.1.dev20220309135113 on 2022-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("escription", models.TextField()),
                ("technology", models.CharField(max_length=20)),
                ("image", models.FilePathField(path="/img")),
            ],
        ),
    ]
