# Generated by Django 4.2.18 on 2025-02-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squashme", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foo",
            old_name="name",
            new_name="rename",
        ),
    ]
