# Generated by Django 4.2.18 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squashme", "0002_rename_name_foo_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="foo",
            name="another_field",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
