# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150920110034 on 2015-09-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='urlconf',
            field=models.CharField(blank=True, max_length=100, verbose_name='URLconf'),
        ),
    ]
