# This file is distributed under the same license as the Django package.
#
# Translators:
# Muḥend Belqasem <belkacem77@gmail.com>, 2017
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-01-19 16:49+0100\n"
"PO-Revision-Date: 2017-10-06 12:00+0000\n"
"Last-Translator: Muḥend Belqasem <belkacem77@gmail.com>\n"
"Language-Team: Kabyle (http://www.transifex.com/django/django/language/"
"kab/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: kab\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "Administrative Documentation"
msgstr ""

msgid "Home"
msgstr "Agejdan"

msgid "Documentation"
msgstr "Tasemlit"

msgid "Bookmarklets"
msgstr ""

msgid "Documentation bookmarklets"
msgstr ""

msgid ""
"To install bookmarklets, drag the link to your bookmarks toolbar, or right-"
"click the link and add it to your bookmarks. Now you can select the "
"bookmarklet from any page in the site."
msgstr ""

msgid "Documentation for this page"
msgstr ""

msgid ""
"Jumps you from any page to the documentation for the view that generates "
"that page."
msgstr ""

msgid "Tags"
msgstr "Tiṛekkizin"

msgid "List of all the template tags and their functions."
msgstr ""

msgid "Filters"
msgstr "Imzizdigen"

msgid ""
"Filters are actions which can be applied to variables in a template to alter "
"the output."
msgstr ""

msgid "Models"
msgstr ""

msgid ""
"Models are descriptions of all the objects in the system and their "
"associated fields. Each model has a list of fields which can be accessed as "
"template variables"
msgstr ""

msgid "Views"
msgstr "Timeẓriyin"

msgid ""
"Each page on the public site is generated by a view. The view defines which "
"template is used to generate the page and which objects are available to "
"that template."
msgstr ""

msgid "Tools for your browser to quickly access admin functionality."
msgstr ""

msgid "Please install docutils"
msgstr ""

#, python-format
msgid ""
"The admin documentation system requires Python's <a href=\"%(link)s"
"\">docutils</a> library."
msgstr ""

#, python-format
msgid ""
"Please ask your administrators to install <a href=\"%(link)s\">docutils</a>."
msgstr ""

#, python-format
msgid "Model: %(name)s"
msgstr ""

msgid "Fields"
msgstr "Urtan"

msgid "Field"
msgstr "Urti"

msgid "Type"
msgstr "Tawsit"

msgid "Description"
msgstr "Aglam"

msgid "Methods with arguments"
msgstr ""

msgid "Method"
msgstr "Tarrayt"

msgid "Arguments"
msgstr "Tiɣira"

msgid "Back to Model documentation"
msgstr ""

msgid "Model documentation"
msgstr ""

msgid "Model groups"
msgstr ""

msgid "Templates"
msgstr "Tineɣrufin"

#, python-format
msgid "Template: %(name)s"
msgstr ""

#, python-format
msgid "Template: \"%(name)s\""
msgstr ""

#. Translators: Search is not a verb here, it qualifies path (a search path)
#, python-format
msgid "Search path for template \"%(name)s\":"
msgstr ""

msgid "(does not exist)"
msgstr "(ula- it)"

msgid "Back to Documentation"
msgstr ""

msgid "Template filters"
msgstr ""

msgid "Template filter documentation"
msgstr ""

msgid "Built-in filters"
msgstr ""

#, python-format
msgid ""
"To use these filters, put <code>%(code)s</code> in your template before "
"using the filter."
msgstr ""

msgid "Template tags"
msgstr ""

msgid "Template tag documentation"
msgstr ""

msgid "Built-in tags"
msgstr ""

#, python-format
msgid ""
"To use these tags, put <code>%(code)s</code> in your template before using "
"the tag."
msgstr ""

#, python-format
msgid "View: %(name)s"
msgstr ""

msgid "Context:"
msgstr "Asatal:"

msgid "Templates:"
msgstr "Tineɣrufin:"

msgid "Back to View documentation"
msgstr ""

msgid "View documentation"
msgstr "Sken tasemlit"

msgid "Jump to namespace"
msgstr ""

msgid "Empty namespace"
msgstr ""

#, python-format
msgid "Views by namespace %(name)s"
msgstr ""

msgid "Views by empty namespace"
msgstr ""

#, python-format
msgid ""
"\n"
"    View function: <code>%(full_name)s</code>. Name: <code>%(url_name)s</"
"code>.\n"
msgstr ""

msgid "tag:"
msgstr "tabzimt:"

msgid "filter:"
msgstr "imzizdig:"

msgid "view:"
msgstr "wali:"

#, python-format
msgid "App %(app_label)r not found"
msgstr ""

#, python-format
msgid "Model %(model_name)r not found in app %(app_label)r"
msgstr ""

msgid "model:"
msgstr "Taneɣruft"

#, python-format
msgid "the related `%(app_label)s.%(data_type)s` object"
msgstr ""

#, python-format
msgid "related `%(app_label)s.%(object_name)s` objects"
msgstr ""

#, python-format
msgid "all %s"
msgstr "akk %s"

#, python-format
msgid "number of %s"
msgstr ""

#, python-format
msgid "%s does not appear to be a urlpattern object"
msgstr ""
