# Generated by Django 4.2.18 on 2025-02-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggerfailingcode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baz",
            name="baz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
