# Generated by Django 3.2.4 on 2021-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
                ('code', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
