match_functions = {'bbcontains': None,
    'bboverlaps': None,
    'contained': None,
    'contains': None,
    'contains_properly': None,
    'coveredby': None,
    'covers': None,
    'crosses': None,
    'disjoint': None,
    'distance_gt': None,
    'distance_gte': None,
    'distance_lt': None,
    'distance_lte': None,
    'dwithin': None,
    'equals': None,
    'exact': None,
    'intersects': None,
    'overlaps': None,
    'relate': None,
    'same_as': None,
    'touches': None,
    'within': None,
    'left': None,
    'right': None,
    'overlaps_left': None,
    'overlaps_right': None,
    'overlaps_above': None,
    'overlaps_below': None,
    'strictly_above': None,
    'strictly_below': None}


