# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(db_index=True)),
                ('channel_name', models.CharField(max_length=512)),
                ('content', models.TextField()),
            ],
        ),
    ]
