# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_recordingSuite0():
    client = WindmillTestClient(__name__)
    client.type(text="Hello", name='q')
    client.click(xpath=u"//span[@id='body']/center/form/table[2]/tbody/tr[8]/td")
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(xpath=u"//div[@id='res']/div/ol/li/h3[1]/a/em")
    client.asserts.assertNode(link=u'How do you say hello in Japanese ? - Yahoo! Answers')
    client.asserts.assertNode(link=u'hello')
    client.asserts.assertNode(link=u'japanese')