from __future__ import unicode_literals

import pickle

from django.contrib.sites.models import Site
from django.core.exceptions import UnpickleException
from django.db import models
from django.test import TestCase
from django.utils.version import get_major_version

from .models.publication import Publication
from .models.article import Article


class Advertisment(models.Model):
    customer = models.CharField(max_length=100)
    publications = models.ManyToManyField(
        "model_package.Publication", null=True, blank=True
    )


class ModelPackageTests(TestCase):
    def test_model_packages(self):
        p = Publication.objects.create(title="FooBar")

        current_site = Site.objects.get_current()
        self.assertEqual(current_site.domain, "example.com")

        # Regression for #12168: models split into subpackages still get M2M
        # tables
        a = Article.objects.create(headline="a foo headline")
        a.publications.add(p)
        a.sites.add(current_site)

        a = Article.objects.get(id=a.pk)
        self.assertEqual(a.id, a.pk)
        self.assertEqual(a.sites.count(), 1)

        # Regression for #12245 - Models can exist in the test package, too
        ad = Advertisment.objects.create(customer="Lawrence Journal-World")
        ad.publications.add(p)

        ad = Advertisment.objects.get(id=ad.pk)
        self.assertEqual(ad.publications.count(), 1)

        # Regression for #12386 - field names on the autogenerated intermediate
        # class that are specified as dotted strings don't retain any path
        # component for the field or column name
        self.assertEqual(
            Article.publications.through._meta.fields[1].name, 'article'
        )
        self.assertEqual(
            Article.publications.through._meta.fields[1].get_attname_column(),
            ('article_id', 'article_id')
        )
        self.assertEqual(
            Article.publications.through._meta.fields[2].name, 'publication'
        )
        self.assertEqual(
            Article.publications.through._meta.fields[2].get_attname_column(),
            ('publication_id', 'publication_id')
        )

        # The oracle backend truncates the name to 'model_package_article_publ233f'.
        self.assertTrue(
            Article._meta.get_field('publications').m2m_db_table() in ('model_package_article_publications', 'model_package_article_publ233f')
        )

        self.assertEqual(
            Article._meta.get_field('publications').m2m_column_name(), 'article_id'
        )
        self.assertEqual(
            Article._meta.get_field('publications').m2m_reverse_name(),
            'publication_id'
        )

    def test_missing_django_version_unpickling(self):
        # test greaceful handling of unpickling of QuerySets pickled
        # in Django version < 1.7
        # See ticket 21430 and associated PR
        class MissingDjangoVersionPublication(Publication):
            def __reduce__(self):
                reduce_list = super(MissingDjangoVersionPublication, self).__reduce__()
                data = reduce_list[-1]
                del data['django_version']
                return reduce_list

        p = MissingDjangoVersionPublication(title="FooBar")
        # Unpickling should raise UnpickleException and not KeyError
        self.assertRaises(UnpickleException, pickle.loads, pickle.dumps(p))

    def test_unsupported_unpickle_exception(self):
        # ticket 21430
        class TestModel(models.Model):
            title = models.CharField(max_length=10)
            def __reduce__(self):
                reduce_list = super(TestModel, self).__reduce__()
                data = reduce_list[-1]
                data['django_version'] = str(float(get_major_version()) - 0.1)
                return reduce_list

        p = TestModel(title="FooBar")
        self.assertRaises(UnpickleException, pickle.loads, pickle.dumps(p))
