# Generated by Django 4.0.3 on 2022-03-15 20:24
from django.db import migrations

def up(apps, schema_editor):
    A = apps.get_model('rmigrate', 'A')
    User = apps.get_model('rmigrate', 'User')

    a = A(user=User.objects.first())
    a.save()

def down(apps, schema_editor):
    A = apps.get_model('rmigrate', 'A')
    print(A.objects.all())

    A.objects.first().delete()
    print(A.objects.all())

class Migration(migrations.Migration):

    dependencies = [
        ('rmigrate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]

