# Generated by Django 5.0.dev20230313110630 on 2023-03-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rmigrate", "0002_create_sample_objects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b",
            name="a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rmigrate.a"
            ),
        ),
    ]
