# Generated by Django 5.0.dev20230601185047 on 2023-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0002_alter_redirect_new_path_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="new_path",
            field=models.TextField(
                blank=True,
                help_text="This can be either an absolute path (as above) or a"
                " full URL starting with a scheme such as “https://”.",
                max_length=2000,
                verbose_name="redirect to",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="old_path",
            field=models.TextField(
                db_index=True,
                help_text="This should be an absolute path, excluding the"
                " domain name. Example: “/events/search/”.",
                max_length=2000,
                verbose_name="redirect from",
            ),
        ),
    ]
