# Generated by Django 6.1.dev20251225192419 on 2025-12-25 20:08

from django.db import migrations, models

from ..fields import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ("postgres_tests", "0002_create_test_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="othertypesarraymodel",
            name="json",
            field=ArrayField(
                base_field=models.JSONField(default=dict), default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="withsizearraymodel",
            name="field",
            field=ArrayField(base_field=models.FloatField(), size=3),
        ),
    ]
