# This file is distributed under the same license as the Django package.
#
# Translators:
# Edgars Andersons, 2025
# Edgars Voroboks <edgars.voroboks@gmail.com>, 2017
# Jannis Leidel <jannis@leidel.info>, 2011
# Māris Nartišs <maris.gis@gmail.com>, 2016
# Edgars Voroboks <edgars.voroboks@gmail.com>, 2019,2021
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-01-15 09:00+0100\n"
"PO-Revision-Date: 2025-09-17 20:19+0000\n"
"Last-Translator: Edgars Andersons, 2025\n"
"Language-Team: Latvian (http://app.transifex.com/django/django/language/"
"lv/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: lv\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : "
"2);\n"

msgid "Administrative Documentation"
msgstr "Pārvaldīšanas dokumentācija"

msgid "Home"
msgstr "Sākums"

msgid "Documentation"
msgstr "Dokumentācija"

msgid "Bookmarklets"
msgstr "Grāmatzīmju sīklietotnes"

msgid "Documentation bookmarklets"
msgstr "Dokumentācijas grāmatzīmes"

msgid ""
"To install bookmarklets, drag the link to your bookmarks toolbar, or right-"
"click the link and add it to your bookmarks. Now you can select the "
"bookmarklet from any page in the site."
msgstr ""
"Lai uzstādītu grāmatzīmju sīklietotni, saiti jāievelk grāmatzīmju rīkjoslā "
"vai ar peles labo pogu jāklikšķina uz saites un jāpievieno tā savām "
"grāmatzīmēm. Tagad vari izvēlēties grāmatzīmju sīklietotni jebkurā vietnes "
"lapā."

msgid "Documentation for this page"
msgstr "Šīs lapas dokumentācija"

msgid ""
"Jumps you from any page to the documentation for the view that generates "
"that page."
msgstr ""
"Pārlec no jebkuras lapas uz tā skata, kas izveido šo lapu, dokumentāciju."

msgid "Tags"
msgstr "Tagi"

msgid "List of all the template tags and their functions."
msgstr "Visu veidņu tagu un to funkciju saraksts."

msgid "Filters"
msgstr "Filtri"

msgid ""
"Filters are actions which can be applied to variables in a template to alter "
"the output."
msgstr ""
"Filtri ir darbības, kuras var tikt pielietotas veidnes mainīgajiem, lai "
"izmainītu izvades iznākumu."

msgid "Models"
msgstr "Modeļi"

msgid ""
"Models are descriptions of all the objects in the system and their "
"associated fields. Each model has a list of fields which can be accessed as "
"template variables"
msgstr ""
"Modeļi ir visu sistēmas objektu un to saistīto lauku apraksti. Katram "
"modelim ir saraksts ar laukiem, kuriem var piekļūt kā veidnes mainīgajiem"

msgid "Views"
msgstr "Skati"

msgid ""
"Each page on the public site is generated by a view. The view defines which "
"template is used to generate the page and which objects are available to "
"that template."
msgstr ""
"Katru lapu publiskajā vietnē izveido skats. Skats nosaka, kuru veidni "
"izmanto lapas izveidošanai un kuri objekti ir pieejami attiecīgajai veidnei."

msgid "Tools for your browser to quickly access admin functionality."
msgstr "Rīki pārlūkam, lai ātri piekļūtu pārvaldīšanas iespējām."

msgid "Please install docutils"
msgstr "Lūgums uzstādīt 'docutils'"

#, python-format
msgid ""
"The admin documentation system requires Python’s <a "
"href=\"%(link)s\">docutils</a> library."
msgstr ""
"Pārvaldīšanas dokumentācijas sistēmai ir nepieciešama Python <a "
"href=\"%(link)s\">docutils</a> bibliotēka."

#, python-format
msgid ""
"Please ask your administrators to install <a href=\"%(link)s\">docutils</a>."
msgstr ""
"Lūgums vaicāt savam pārvaldītājam uzstādīt <a href=\"%(link)s\">docutils</a>."

#, python-format
msgid "Model: %(name)s"
msgstr "Modelis: %(name)s"

msgid "Fields"
msgstr "Lauki"

msgid "Field"
msgstr "Lauks"

msgid "Type"
msgstr "Veids"

msgid "Description"
msgstr "Apraksts"

msgid "Methods with arguments"
msgstr "Metodes ar parametriem"

msgid "Method"
msgstr "Metode"

msgid "Arguments"
msgstr "Parametrs"

msgid "Back to Model documentation"
msgstr "Atpakaļ uz modeļu dokumentāciju"

msgid "Model documentation"
msgstr "Modeļu dokumentācija"

msgid "Model groups"
msgstr "Modeļu kopas"

msgid "Templates"
msgstr "Veidnes"

#, python-format
msgid "Template: %(name)s"
msgstr "Veidne: %(name)s"

#, python-format
msgid "Template: <q>%(name)s</q>"
msgstr "Veidne: <q>%(name)s</q>"

#. Translators: Search is not a verb here, it qualifies path (a search path)
#, python-format
msgid "Search path for template <q>%(name)s</q>:"
msgstr "Veidnes <q>%(name)s</q> ceļš:"

msgid "(does not exist)"
msgstr "(nepastāv)"

msgid "Back to Documentation"
msgstr "Atpakaļ uz dokumentāciju"

msgid "Template filters"
msgstr "Veidnes filtri"

msgid "Template filter documentation"
msgstr "Veidņu filtru dokumentācija"

msgid "Built-in filters"
msgstr "Iebūvētie filtri"

#, python-format
msgid ""
"To use these filters, put <code>%(code)s</code> in your template before "
"using the filter."
msgstr ""
"Lai izmantotu šos filtrus, veidnē jāievieto <code>%(code)s</code> pirms "
"filtra izmantošanas."

msgid "Template tags"
msgstr "Veidņu tagi"

msgid "Template tag documentation"
msgstr "Veidņu tagu dokumentācija"

msgid "Built-in tags"
msgstr "Iebūvētie tagi"

#, python-format
msgid ""
"To use these tags, put <code>%(code)s</code> in your template before using "
"the tag."
msgstr ""
"Lai izmantotu šos tagus, veidnē jāieviet <code>%(code)s</code> pirms taga "
"izmantošanas."

#, python-format
msgid "View: %(name)s"
msgstr "View: %(name)s"

msgid "Context:"
msgstr "Konteksts:"

msgid "Templates:"
msgstr "Veidnes:"

msgid "Back to View documentation"
msgstr "Atpakaļ uz skatu dokumentācijas"

msgid "View documentation"
msgstr "Skatu dokumentācija"

msgid "Jump to namespace"
msgstr "Pārlēkt uz nosaukumu telpu"

msgid "Empty namespace"
msgstr "Tukša nosaukumu telpa"

#, python-format
msgid "Views by namespace %(name)s"
msgstr "Skati pēc nosaukumu telpas %(name)s"

msgid "Views by empty namespace"
msgstr "Skati pēc tukšas nosaukumu telpas"

#, python-format
msgid ""
"\n"
"    View function: <code>%(full_name)s</code>. Name: <code>%(url_name)s</"
"code>.\n"
msgstr ""
"\n"
"    Skata funkcija: <code>%(full_name)s</code>. Nosaukums: "
"<code>%(url_name)s</code>.\n"

msgid "tag:"
msgstr "tags:"

msgid "filter:"
msgstr "filtrs:"

msgid "view:"
msgstr "skats:"

#, python-format
msgid "App %(app_label)r not found"
msgstr "Lietotne %(app_label)r netika atrasta"

#, python-format
msgid "Model %(model_name)r not found in app %(app_label)r"
msgstr "Modelis  %(model_name)r lietotnē %(app_label)r nav atrasts"

msgid "model:"
msgstr "modelis:"

#, python-format
msgid "the related `%(app_label)s.%(data_type)s` object"
msgstr "saistītais `%(app_label)s.%(data_type)s` objekts"

#, python-format
msgid "related `%(app_label)s.%(object_name)s` objects"
msgstr "saistītie `%(app_label)s.%(object_name)s` objekti"

#, python-format
msgid "all %s"
msgstr "visi %s"

#, python-format
msgid "number of %s"
msgstr "%s skaits"

#, python-format
msgid "%s does not appear to be a urlpattern object"
msgstr "neizskatās, ka%s ir urlpattern objekts"
