name: "Check test migrations"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install the checked-out Django package in editable mode so tests
          # reference the repo source.
          pip install -e .
      - name: Run makemigrations --check for test apps
        working-directory: .
        run: |
          python scripts/check_test_migrations.py
        env:
          DJANGO_SETTINGS_MODULE: test_sqlite
