name: Visual Regression Tests

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  selenium-screenshots:
    if: contains(join(github.event.pull_request.labels.*.name, '|'), 'screenshots')
    runs-on: ubuntu-latest
    name: Screenshots
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: 'tests/requirements/py3.txt'
      - name: Update apt repo
        run: sudo apt update
      - name: Install libmemcached-dev for pylibmc
        run: sudo apt install -y libmemcached-dev
      - name: Install and upgrade packaging tools
        run: python -m pip install --upgrade pip wheel
      - run: python -m pip install -r tests/requirements/py3.txt -e .

      - name: Run Selenium tests with screenshots
        working-directory: ./tests/
        run: python -Wall runtests.py --verbosity=2 --noinput --selenium=chrome --headless --screenshots --settings=test_sqlite --parallel=1

      - name: Cache oxipng
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo

      - name: Install oxipng
        run: which oxipng || cargo install oxipng

      - name: Optimize screenshots
        run: oxipng --interlace=0 --opt=4 --strip=safe tests/screenshots/*.png

      - name: Organize screenshots
        run: |
          mkdir --parents "/tmp/screenshots/${{ github.event.pull_request.head.sha }}"
          mv tests/screenshots/* "/tmp/screenshots/${{ github.event.pull_request.head.sha }}/"

      - name: Upload screenshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-${{ github.event.pull_request.head.sha }}
          path: /tmp/screenshots/
          if-no-files-found: error
